### ISSUE TITLE
Logo request

### ISSUE THREAD

**Issue by SevenOutman** [nunojesus/graphic-design-portfolio#6]
Hi there,
I've heard of your open source logo design project and just think it's awesome. I notice that you seem to be especially interested in music player projects, so maybe you'll also be interested in my open source project [Vue-APlayer](https://github.com/SevenOutman/vue-aplayer).
It started back in 2016 and is under regular maintenance. Since it's a reimplementation of [APlayer](https://github.com/DIYgod/APlayer) with Vue library, I took APlayer's logo - a white play button - added Vue's theme color to it, and used it as my project's logo for now. Would you like to help me with a better logo?

**Comment by nunojesus** [comment]
Hello, thank you for your contact, I will help you  for sure I will open a issue on your repository to start the work.
Thank you!
